### ISSUE TITLE
"Inline local variable" produces broken code with JLS >= 1.8

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#2775]
Follow up from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2536.

Found while analyzing test failure of `org.eclipse.jdt.ui.tests.refactoring.InlineTempTests.test31()` in https://download.eclipse.org/eclipse/downloads/drops4/I20240725-1800/testresults/html/org.eclipse.jdt.ui.tests.refactoring_ep433I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

The test worked with the project compliance set to 1.4 or 1.5 (not sure which was used in the hierarchy of the test).
With the project compliance 1.8 inline refactoring of `emptyMap` variable produces compilation error at line `Integer first= Collections.emptyMap(/*nada*/).values().iterator().next();`

**In**
```
import java.util.Collections;
import java.util.Map;

class A extends Sup<String> {
	public A(Map<String, Integer> map) {
		Map<String, Integer> emptyMap= Collections.emptyMap(/*nada*/);
		method(emptyMap);
		method2(emptyMap);
		method3(emptyMap);
		new A(emptyMap);
		super.sup(emptyMap);
		
		Map<String, Integer> emptyMap2= emptyMap;
		emptyMap2= emptyMap;
		Object o= emptyMap;
		Map<? extends String, ?> emptyMap3= emptyMap;
		
		Integer first= emptyMap.values().iterator().next();
	}

	void method(Map<String, Integer> map) { }
	void method2(Map<? extends String, ?> map) {	}
	void method3(Object map) {	}
}

class Sup<S> {
	<A extends S, B> void sup(Map<A, B> map) {}
}
```

**Out after "inline local variable"**
```
import java.util.Collections;
import java.util.Map;

class A extends Sup<String> {
	public A(Map<String, Integer> map) {
		method(Collections.emptyMap(/*nada*/));
		method2(Collections.emptyMap(/*nada*/));
		method3(Collections.emptyMap(/*nada*/));
		new A(Collections.emptyMap(/*nada*/));
		super.sup(Collections.emptyMap(/*nada*/));
		
		Map<String, Integer> emptyMap2= Collections.emptyMap(/*nada*/);
		emptyMap2= Collections.emptyMap(/*nada*/);
		Object o= Collections.emptyMap(/*nada*/);
		Map<? extends String, ?> emptyMap3= Collections.emptyMap(/*nada*/);
		
		Integer first= Collections.emptyMap(/*nada*/).values().iterator().next(); // <----- ERROR here
	}

	void method(Map<String, Integer> map) { }
	void method2(Map<? extends String, ?> map) {	}
	void method3(Object map) {	}
}

class Sup<S> {
	<A extends S, B> void sup(Map<A, B> map) {}
}
```

**Comment by iloveeclipse** [comment]
> I am not familiar with the jdt.core code that would have changed this

Did it ever worked in post-1.4 world?

**Comment by datho7561** [comment]
> Did it ever worked in post-1.4 world?

I'm suspicious about it having ever worked as well.

I was playing around with a quick fix test case that interacts with type variables recently that only ever worked properly pre 1.5 because it relied on getting the erasure of the type. (I'll file it separately).

**Comment by jjohnstn** [comment]
@datho7561 @iloveeclipse More info.  I found the change in behavior.  The flag: InferenceContext.hasExplicitExpectedType is only set in ParameterizedGenericMethodBinding.computeCompatibleMethod().  This method has a check for >= 1.8 and calls: computeCompatibleMethod18() which bypasses the logic which sets the flag.  Without the flag set, the refactoring will never know to add the parameter types.  I think that the computeCompatibleMethod18() needs to set the flag.

**Comment by jjohnstn** [comment]
... or the logic which uses the flag needs to check another flag set by computeCompatibleMethod18()

**Comment by stephan-herrmann** [comment]
> I think that the computeCompatibleMethod18() needs to set the flag.

What exactly should the flag signal? 
* Whether type inference was generally involved for this invocation?
* Whether specifically the return type was determined by inference?

The former could probably be determined from `org.eclipse.jdt.internal.compiler.ast.MessageSend.inferenceContexts`.

The latter might require more work. Would it help to compare `ParameterizedGenericMethodBinding.returnType` with `ParameterizedGenericMethodBinding.originalMethod.returnType`?

**Comment by jjohnstn** [comment]
@stephan-herrmann I believe I am out of my league here :), but I believe it to be the latter.  I tried the following change in DefaultBindingResolver:

```

	@Override
	boolean isResolvedTypeInferredFromExpectedType(MethodInvocation methodInvocation) {
		Object oldNode = this.newAstToOldAst.get(methodInvocation);
		if (oldNode instanceof MessageSend) {
			MessageSend messageSend = (MessageSend) oldNode;
			org.eclipse.jdt.internal.compiler.lookup.MethodBinding methodBinding = messageSend.binding;
			if (methodBinding instanceof ParameterizedGenericMethodBinding) {
				ParameterizedGenericMethodBinding genericMethodBinding = (ParameterizedGenericMethodBinding) methodBinding;
				return genericMethodBinding.inferredReturnType || genericMethodBinding.wasInferred;
			}
		}
		return false;
	}

```

which simply added using the wasInferred flag and that does indeed fix the UI test, but I do not know if that is correct or not.  I was going to try and push a PR to see if it broke anything outside of some UI tests that were recently changed due to the missing type parameters.
