### PR TITLE
Fix native varargs methods incorrectly treated as signature-polymorphic #4955

### PR DESCRIPTION
**Pull request by kaluchi**
Regression from #147: `hasPolymorphicSignature()` used `id`-based comparison to check if a method's declaring class is `MethodHandle` or `VarHandle`. Since neither type has a pre-assigned `TypeId`, both default to `id = 0` — same as any user-defined class. The comparison `0 == 0` caused false positives.

**Effect:** Any `static native void foo(Object... args)` method on any class was treated as signature-polymorphic. ECJ generated `invokestatic` with direct argument types (e.g. `debug(String)`) instead of the varargs descriptor (`debug(Object[])`), causing `NoSuchMethodError` at runtime.

**Fix:** Replace `declaringClassLocal.id == scope.getJavaLangInvokeMethodHandle().id` with `TypeBinding.equalsEquals(declaringClassLocal, scope.getJavaLangInvokeMethodHandle())`.

**Regression test:** `BatchCompilerTest2.testGH4955()` — compiles a class with `static native void debug(Object... args)`, verifies the disassembled bytecode uses `Object[]` descriptor.

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4955

### CODE REVIEW

**Comment by srikanth-sankaran** [comment]
> Regression from #147: `hasPolymorphicSignature()` used `id`-based comparison to check if a method's declaring class is `MethodHandle` or `VarHandle`. Since neither type has a pre-assigned `TypeId`, both default to `id = 0` — same as any user-defined class. The comparison `0 == 0` caused false positives.

These assertions seem faulty. Types start with a default value of `org.eclipse.jdt.internal.compiler.lookup.TypeIds.NoId` and not with a value of `0` and get stamped with a _well known type id_ or a highwater mark id when _some derivation happens_.

In the provided regression test (without the fix) I see `MethodHandle` has an id of 156 and actually fails the == comparison which then ends up succeeding with the `VarHandle` comparison as both the declaring class and `VarHandle` end up having `NoId`.

Certainly the original code is suspect - I don't know why a direct comparison of `id` should be attempted at all. Type comparisons can/should be done with `==/!=` for identity comparisons and `equalsEquals/notEquals` for annotation agnostic comparisons.

File: org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/MethodBinding.java [hunk 1]
```diff
@@ -1444,8 +1444,8 @@ public boolean hasPolymorphicSignature(Scope scope) {
 		 */
 		if (this.parameters[0].leafComponentType().id == TypeIds.T_JavaLangObject) {
 			ReferenceBinding declaringClassLocal = this.declaringClass;
-			if ((declaringClassLocal != null) && (declaringClassLocal.id == scope.getJavaLangInvokeMethodHandle().id
-					|| declaringClassLocal.id == scope.getJavaLangInvokeVarHandle().id)) {
+			if ((declaringClassLocal != null) && (TypeBinding.equalsEquals(declaringClassLocal, scope.getJavaLangInvokeMethodHandle())
+					|| TypeBinding.equalsEquals(declaringClassLocal, scope.getJavaLangInvokeVarHandle()))) {
```
Comment (srikanth-sankaran) [inline org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/MethodBinding.java]: The null check is noise and can be elided.

Please remove the original comment: It is just noise with no value. 

```
/*
		 *  here type will be arrayType we will come here only if the method is of type
		 *  varargs(represented by arraytype) and with only one parameter.
		 */
```

How about the method simply reading:

```
public boolean hasPolymorphicSignature(Scope scope) {
	if ((this.tagBits & TagBits.AnnotationPolymorphicSignature) != 0) {
		return true;
	}
	return this.isNative() && this.isVarargs() && this.parameters.length == 1 &&
				this.parameters[0].leafComponentType().id == TypeIds.T_JavaLangObject &&
					(TypeBinding.equalsEquals(this.declaringClass, scope.getJavaLangInvokeMethodHandle())
							|| TypeBinding.equalsEquals(this.declaringClass, scope.getJavaLangInvokeVarHandle()));
}
```

This looks much cleaner to me. I didn't run the tests

**Comment by srikanth-sankaran** [comment]
Thanks for your efforts here @kaluchi !

File: org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/MethodBinding.java (hunk 1 above)
Comment (srikanth-sankaran) [reply org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/MethodBinding.java]: The set check for the bit `AnnotationPolymorphicSignature` could also be pushed into the return statement, but that perhaps degrades readability.

**Comment by kaluchi** [comment]
@srikanth-sankaran Thanks for the quick feedback! Applied the suggested cleanup.

**Comment by srikanth-sankaran** [comment]
@jarthana - Could you look through too and take it forward ? TIA.
