### ISSUE TITLE
PDE/Build is broken since #181

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#619]
The refactoring #181 broke the integration of ecj into PDE/Build and the application `org.eclipse.ant.core.antRunner`.

This results in fatal error `Class org.eclipse.jdt.core.JDTCompilerAdapter could not be loaded because of an invalid dependency.`

While few projects still use PDE/Build (Object Teams successfully does), this also breaks the Plug-in Export wizard.

**To reproduce** simply create a hello world plug-in and try to **Export ... > Deployable plug-ins and fragments**.

That integration is supposed to work via this extension (in org.eclipse.jdt.core):

```
<extension 
	point="org.eclipse.ant.core.extraClasspathEntries">
	<extraClasspathEntry
		library="jdtCompilerAdapter.jar">
	</extraClasspathEntry>
</extension> 
```

This ensures that class `org.eclipse.jdt.core.JDTCompilerAdapter` can be loaded via Ant's classloader (it needs to find the superclass org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter).

I don't fully understand what's going on, but in the bad case I observed JDTCompilerAdapter being found in `org.eclipse.jdt.core.compiler.batch`, but then it cannot find its superclass via that plugin (which has ant.jar on it's buildpath but not in its runtime dependencies). As a result `NoClassDefFoundError` is thrown - reported (bogusly) against JDTCompilerAdapter.

Anyway, seeing JDTCompilerAdapter.java in o.e.j.core.compiler.batch, whereas jdtCompilerAdapter.jar is still in o.e.j.core is definitely inconsistent.

**Comment by stephan-herrmann** [comment]
@iloveeclipse  in commit 1632584676246674f0b28d183a1049e1c80afd89 you "Really fix[ed] jdtCompilerAdapter.jar generation for pde/ant support", but for me this doesn't work, and fetching class files from another plug-ins target folder looks weird to say the least. Can you explain why you came up with this solution? It seems you fought a variant of the same problem already (https://github.com/eclipse-pde/eclipse.pde/issues/419)
* what would break if we move JDTCompilerAdapter.java back to org.eclipse.jdt.core?
* alternatively, could we move the above extension to o.e.j.core.compiler.batch?

I believe we really need to have JDTCompilerAdapter.java/.class and jdtCompilerAdapter.jar in the same plug-in.

**Comment by iloveeclipse** [comment]
@stephan-herrmann : I believe it is a duplicate of https://github.com/eclipse-pde/eclipse.pde/issues/419.
I'm not sure which build you are using, please try latest nightly.

See https://github.com/eclipse-jdt/eclipse.jdt.core/tree/master/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/core for the summary how the things are supposed to work with ant.

**Comment by stephan-herrmann** [comment]
>  I'm not sure which build you are using, please try latest nightly.

I'm using I20221205-0710, which I identified as the point when the ecj-refactoring was complete. For Object Teams I very much hoped I could adopt #181 without intermingled code changes. Apparently, this is not possible :(

BTW, we could have avoided many hours of analysis on my side, if https://github.com/eclipse-pde/eclipse.pde/issues/419 had been linked from #181 :( 

I will merge with I20221207-1800 and report back.

**Comment by stephan-herrmann** [comment]
> See https://github.com/eclipse-jdt/eclipse.jdt.core/tree/master/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/core for the summary how the things are supposed to work with ant.

Thanks for the write-up. This closely matches my observations. Apparently, JDTCompilerAdapter.java is where standalone and OSGi use of ecj are at conflict, leading to the funny situation that it **must** reside in org.eclipse.jdt.core.compiler.batch but in OSGi mode, **nobody** should ever access it via that plug-in. Glad you found a workaround  (truly looks like dead code: not used internally nor exported => definitely worth the documentation).

Speaking of documentation: any idea how to integrate the new README.md with https://wiki.eclipse.org/JDT_Core_Programmer_Guide/ECJ ?

**Comment by stephan-herrmann** [comment]
> I will merge with I20221207-1800 and report back.

With I20221207-1800 I can indeed build again, thanks @iloveeclipse !

Closing as duplicate of https://github.com/eclipse-pde/eclipse.pde/issues/419.
