### ISSUE TITLE
[Records] private static class in record used in an annotation is allowed by ECJ but not javac

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.core#3046]
```java
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Annot(using = Rec.Inner.class)
public record Rec() {

	private static class Inner {}
}

@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@interface Annot {

    public Class<?> using();
}
```

Compiles in Eclipse 4.32 and 4.33, but javac 23 and 22 give the error:
```
Rec.java:8: error: Inner has private access in Rec
@Annot(using = Rec.Inner.class)
                  ^
```

I took a quick look at the JLS: https://docs.oracle.com/javase/specs/jls/se22/html/jls-8.html#jls-8.10.3. `private static` classes are allowed in records, and they compile in both ecj and javac, but when they are used in an annotation there's something else that's going on. Package-level access compiles in javac.

**Comment by srikanth-sankaran** [comment]
Very likely same as #1216

**Comment by iloveeclipse** [comment]
Removed out-of-date 4.34 milestone. Please set valid one if needed.
