### ISSUE TITLE
Compilation error with generics in 2025-09

### ISSUE THREAD

**Issue by vtintillier** [eclipse-jdt/eclipse.jdt.core#4402]
This code starts failing compilation in 2025-09. Works fine in 2025-06 and `javac`.
It is quite strange as compilation of one expression depends of what was compiled on an earlier line...

Eclipse JDT version is `3.20.300.v20250905-1111`.
Worked with version `3.20.200.v20250528-1830` (2025-06).

```java
package test;

import java.util.Collection;

public class Main {

	void test() {
		ArrayNode results = new ArrayNode();

		// those first two compile fine
		assertThat(results, jsonArray(empty()));
		assertThat(results, jsonArray(contains(jsonObject().where("Id", jsonText("dataset-a")),
				jsonObject().where("Id", jsonText("dataset-b")))));
		/*
		 * this one fails compilation:
		 * The method jsonArray(Main.Matcher<? super Collection<? extends Main.JsonNode>>) in the type Main is not applicable for the arguments (Main.Matcher<Iterable<? extends capture#3-of ? extends Main.JsonNode>>)
		 * 
		 * However it will compile fine if I comment out lines 12-13
		 */
		assertThat(results, jsonArray(contains(jsonObject().where("Id", jsonText("dataset-b")))));
		/*
		 * this one fails compilation:
		 * The method jsonArray(Main.Matcher<? super Collection<? extends Main.JsonNode>>) in the type Main is not applicable for the arguments (Main.Matcher<Iterable<? extends capture#3-of ? extends Main.JsonNode>>)
		 * 
		 * However it will compile fine if I comment out lines 12-13 AND 20
		 */
		assertThat(results, jsonArray(contains(jsonObject().where("Id", jsonText("dataset-@1")),
				jsonObject().where("Id", jsonText("dataset-@2")))));
	}

	public static abstract class JsonNode {
	}

	public static class ArrayNode extends ContainerNode<ArrayNode> {
	}

	public static abstract class ContainerNode<T extends ContainerNode<T>> extends JsonNode {
	}

	public class ObjectNode extends ContainerNode<ObjectNode> {
	}

	public class TextNode extends JsonNode {
	}

	public interface Matcher<T> {
	}

	public static <E> Matcher<java.util.Collection<? extends E>> empty() {
		return null;
	}

	public static <T> void assertThat(T actual, Matcher<? super T> matcher) {
	}

	@SafeVarargs
	public static <E> Matcher<java.lang.Iterable<? extends E>> contains(Matcher<? super E>... itemMatchers) {
		return null;
	}

	public static Matcher<JsonNode> jsonArray(Matcher<? super Collection<? extends JsonNode>> elementsMatcher) {
		return null;
	}

	public static IsJsonObject jsonObject() {
		return null;
	}

	public static Matcher<JsonNode> jsonText(String text) {
		return null;
	}

	public static class IsJsonArray extends AbstractJsonNodeMatcher<ArrayNode> {
	}

	public static class IsJsonObject extends AbstractJsonNodeMatcher<ObjectNode> {
		public IsJsonObject where(String key, Matcher<? super JsonNode> valueMatcher) {
			return null;
		}
	}

	public static class IsJsonText extends AbstractJsonNodeMatcher<TextNode> {
	}

	public static abstract class AbstractJsonNodeMatcher<A extends JsonNode> implements Matcher<JsonNode> {
	}
}
```

**Comment by foal** [comment]
I think it can be related to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4332 or https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4392

**Comment by foal** [comment]
I also faced a similar issue. For me the current version is unusable. Waiting for hot-fix but the only one term that I see 4.38M2 in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4392

**Comment by vtintillier** [comment]
What is strange here is that if I comment out the expression that compiles, then the next expression starts compiling.

**Comment by kaluchi** [comment]
faced same problem, comment for tracking purpose

**Comment by stephan-herrmann** [comment]
Thanks, the observation that an error at one location depends on existence of an independent prior statement is very interesting, and pointed me to a subtle bug introduced in #4104: we correctly added capturing to `ParameterizedTypeBinding.superInterfaces()` but those captures are context specific (see `CapturingContext`) and thus must not be persisted in field `superInterfaces`.
