### ISSUE TITLE
Refactor renames random java elements

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.core#358]
Very nasty regression (random results - but reproducible):
ALT+SHIFT+R on a method sometimes also selects and refactors code that has nothing todo with it.
Example:
![image](https://user-images.githubusercontent.com/51790620/187499163-c1b26aec-84db-43b7-8ad2-055efdb05d76.png)

I wanted to refactor the name of "waitFor" but in the same turn it refactored "lockAcquiringRunnable"
![image](https://user-images.githubusercontent.com/51790620/187499752-d346f2da-667e-4d58-b31f-554a41c57cf9.png)
When i slightly change the code then either problem is gone or other elements are refactored:
![image](https://user-images.githubusercontent.com/51790620/187501093-31fdda92-39f6-46cf-bf64-68b7b653263b.png)

You can download the the example from https://github.com/jukzi/eclipse.platform/commits/refactorBug
```
git clone git@github.com:jukzi/eclipse.platform.git
git checkout refactorBug

```
Then import the `project eclipse.platform\runtime\tests\org.eclipse.core.tests.runtime` to your workspace.
It will have many compilation errors if you do not have the dependencies but that does not affect the bug.

Sorry, that i could not find a smaller example .. as soon as i reduce it i can't reproduce.

Feels like there is a comparison of a colliding hash instead of checking for equals.

**Comment by jukzi** [comment]
@jjohnstn this is a regression from https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/c8ab3558cf8d482557e53d04f26e2713535580ed#diff-b1a1111fa629b3734055f042bc05d0f31f670107db239bdabb47863a290e5cfdR290

The `iMethod.getNameRange()` may belong to another `root` CompilationUnit then the current file.
For the example given in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/358#issue-1356089362  the `iMethod.getNameRange()` returns the range for the Method "waitFor" in the File "RandomOrder.java" while the `root` is the "OrderedLockTest2.java" currently edited. Searching the ASTNode for a range that meant to be in annother file then finds a wrong hit in the current file. (https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/ui%20refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameLinkedMode.java#L285)

please move this issue to jdt.ui
