### ISSUE TITLE
Reconsider interning of capture bindings

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2419]
From #2321: 

Consider this example:
```
class Test {
    public void test() {
    	B<?> b1 = new B<>();
    	B<?> b2 = new B<>();
        A<B<?>> a = this::error; // This makes both B<?> parameters use the same capture variable
    }
    public <T> void error(B<T> a, B<T> b) {}
    interface A<T> {
        void run(T t1, T t2);
    }
    class B<T> {}
}
```
ecj accepts the assignment while javac rejects, saying:
```
 error: incompatible types: invalid method reference
                A<B<?>> a = this::error; // This makes both B<?> parameters use the same capture variable
                            ^
    method error in class Test cannot be applied to given types
      required: Test.B<T>,Test.B<T>
      found:    Test.B<?>,Test.B<?>
      reason: inference variable T has incompatible equality constraints CAP#1,CAP#2
  where T is a type-variable:
    T extends Object declared in method <T>error(Test.B<T>,Test.B<T>)
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
```

Debugging inference for this assignment I can see that descriptorParametersAsArgumentExpressions() answers twice the same type `B<capture#1-of ?>` in the position where javac seems to create two distinct captures.

ecj unifies both types because TypeSystem.getCapturedWildcard() is invoked twice with the exact same ingredients (same wildcard and same source positions), and so the capture is shared. Given that both parameter types originate from the same type variable `<T>` this unification seems justified by common sense, but frankly this is not spelled out in JLS. [5.1.10. Capture Conversion](https://docs.oracle.com/javase/specs/jls/se22/html/jls-5.html#jls-5.1.10)  unconditionally speaks of "a fresh type variable".

This "interning" was introduced in commit 2156fedd. When I disable it, I see the same two errors as reported by javac, but also regressions in:
* NegativeLambdaExpressionsTest.test432759()
* LambdaExpressionTest: test577466, testBug577719, testBug577719_2, testIssue2065
* GenericTypeTest:
  * test0394, test0459, test0684, test0685, test0946, test1363, test426836, test434118
  * this might actually improve: test0884 (see comment in the test)
* GenericsRegressionTest_1_8: testBug424710, testBug425798, testBug426836, testBug432110

To check:
* are those regressions actual failures, or perhaps some would align us better with javac?
* perhaps interning isn't bad per se but the fake arguments of a reference expression should still get distinct captures (although we don't have distinct source positions).

**Comment by stephan-herrmann** [comment]
Duplicate of #2351

**Comment by stephan-herrmann** [comment]
In https://mail.openjdk.org/pipermail/compiler-dev/2025-October/031866.html Vicente replied to a similar issue:
> we also do some capture caching in javac but it is very limited, I would love to extend its reach, but still we would need some spec blessing here

**Comment by stephan-herrmann** [comment]
Inspired by https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4838#issuecomment-4602725736 I made a q-n-d experiment in the direction that CapturingContext.maybeCapture(ReferenceBinding) would never produce the same capture twice. Result: 
* GenericsRegressionTest_9.testGH4039() aligned with javac (rejecting)
* but also new failures in
   * GenericTypeTest.test0836()
   * GenericsRegressionTest.testGH4314b()
   * GenericsRegressionTest.testGH4314c()
   * GenericsRegressionTest_9.testGH3457()
   * GenericsRegressionTest_9.testGH3457c()
   * GenericsRegressionTest_9.testGH4402()

At least for those tests in GenericsRegressionTest_9 I can immediately say that these would be regressions, as congruence with javac has just been asserted (https://github.com/eclipse-jdt/eclipse.jdt.core/pull/5098).

For a moment I thought that perhaps type inference should record the location of expressions that are used during inference, to let different locations create distinct captures, but in the case of testGH4039() there is only one source location driving all this: `Collections.sort(l)`, where `l` is the expression that introduces the wildcard as `List<Cranberry<?>>`. Moreover, both capturing operations ask the supertype of the exact same subtype `Cranberry<?>`.

**Comment by coehlrich** [comment]
I checked `GenericsRegressionTest_9.testGH3457()` and when reducing the `TypeToken` argument ecj gets `T#0 :> capture#1-of ?` while javac gets `T :> Test.B2`

ecj gets `T#0 :> capture#1-of ?` using this:
```
Reduced	⟨new TypeToken<A2<?>>() {
          x() {
            super();
          }
        } → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
  to   	⟨new Test.TypeToken<Test.A2<?>>(){} → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
Reduced	⟨new Test.TypeToken<Test.A2<?>>(){} → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
  to   	⟨new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
Reduced	⟨new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
  to   	⟨Test.A2<?> <= ? extends Test.A1<? extends T#0>⟩
Reduced	⟨Test.A2<?> <= ? extends Test.A1<? extends T#0>⟩
  to   	⟨Test.A2<?> <: Test.A1<? extends T#0>⟩
Reduced	⟨Test.A2<?> <: Test.A1<? extends T#0>⟩
  to   	⟨capture#1-of ? <= ? extends T#0⟩
Reduced	⟨capture#1-of ? <= ? extends T#0⟩
  to   	⟨capture#1-of ? <: T#0⟩
Reduced	⟨capture#1-of ? <: T#0⟩
  to   	TypeBound  T#0 :> capture#1-of ?
```
while javac essentially gets `T#0 :> Test.B2` using this:
```
Reduced	⟨new TypeToken<A2<?>>() {
          x() {
            super();
          }
        } → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
  to   	⟨new Test.TypeToken<Test.A2<?>>(){} → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
Reduced	⟨new Test.TypeToken<Test.A2<?>>(){} → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
  to   	⟨new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
Reduced	⟨new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
  to   	⟨Test.A2<?> <= ? extends Test.A1<? extends T#0>⟩
Reduced	⟨Test.A2<?> <= ? extends Test.A1<? extends T#0>⟩
  to   	⟨Test.A2<?> <: Test.A1<? extends T#0>⟩
Reduced	⟨Test.A2<?> <: Test.A1<? extends T#0>⟩
  to   	⟨? <= ? extends T#0⟩
Reduced	⟨? <= ? extends T#0⟩
  to   	⟨Test.B2 <: T#0⟩
Reduced	⟨Test.B2 <: T#0⟩
  to   	TypeBound  T#0 :> Test.B2
```

- For `new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>` javac would capture.
- For `Test.A2<?> <: Test.A1<? extends T#0>` javac doesn't capture since the check for if a wildcard contains a type calls `isSubtypeNoCapture` when checking.
- For `? <= ? extends T#0` javac obtains `Test.B2` from the upper bound for the type variable.

**Comment by srikanth-sankaran** [comment]
@coehlrich if you have additional logging/instrumentation code for javac, please share a diff here so I can integrate it with what I have. TIA

**Comment by coehlrich** [comment]
I don't have additional logging for javac. The inference information that I put in my previous comment is copy pasted from the inference log from ecj and then changed to match what javac was doing.

**Comment by srikanth-sankaran** [comment]
> I don't have additional logging for javac. The inference information that I put in my previous comment is copy pasted from the inference log from ecj and then changed to match what javac was doing.

I see. 

Let me join @stephan-herrmann in recording our appreciation for all your efforts in addressing/exposing/explaining type inference behavioral differences between javac and ECJ. Please continue to stay engaged and let us bring the compilers as close together as possible.

**Comment by srikanth-sankaran** [comment]
> I checked `GenericsRegressionTest_9.testGH3457()` and when reducing the `TypeToken` argument ecj gets `T#0 :> capture#1-of ?` while javac gets `T :> Test.B2`

For this case, the latest instrumentation produces the trace:

```
TraceOut: (Speculative) (BASIC)  attempt to instantiate method: <T> error(Test.TypeToken<? extends Test.A1<? extends T>>)void with arguments: <anonymous Test.TypeToken<Test.A2<?>>>
TraceOut: Initial Bound Set (B0):
TraceOut:         Inference variable = T 
TraceOut:             T <: Test.B1
TraceOut: Bound set after Invocation Applicability Inference (B2): 
TraceOut:         Inference variable = T 
TraceOut:             T <: Test.B1
TraceOut:             T :> Test.B2
TraceOut: -------------  Inference variables to be solved: T
TraceOut: -------------   Performing graph inference step EQ_LOWER ----------
TraceOut: Bound set after resolution: 
TraceOut:         Inference variable = T instantiation = Test.B2 
TraceOut:             T <: Test.B1
TraceOut:             T :> Test.B2
TraceOut: Instantiated Method Type : (Test.TypeToken<? extends Test.A1<? extends Test.B2>>)void
TraceOut: -----------------------------------------------
TraceOut: (Final) (BASIC)  attempt to instantiate method: <T> error(Test.TypeToken<? extends Test.A1<? extends T>>)void with arguments: <anonymous Test.TypeToken<Test.A2<?>>>
TraceOut: Initial Bound Set (B0):
TraceOut:         Inference variable = T 
TraceOut:             T <: Test.B1
TraceOut: Bound set after Invocation Applicability Inference (B2): 
TraceOut:         Inference variable = T 
TraceOut:             T <: Test.B1
TraceOut:             T :> Test.B2
TraceOut: Bound set after incorporation: <Ditto>
TraceOut: -------------  Inference variables to be solved: T
TraceOut: -------------   Performing graph inference step EQ_LOWER ----------
TraceOut: Bound set after resolution: 
TraceOut:         Inference variable = T instantiation = Test.B2 
TraceOut:             T <: Test.B1
TraceOut:             T :> Test.B2
TraceOut: Instantiated Method Type : (Test.TypeToken<? extends Test.A1<? extends Test.B2>>)void
TraceOut: -----------------------------------------------
TraceOut: (Speculative) (BASIC)  attempt to instantiate method: <T> requireNonNull(T,java.util.function.Supplier<java.lang.String>)T with arguments: java.lang.Object
TraceOut: Initial Bound Set (B0):
TraceOut:         Inference variable = T 
TraceOut: ***************************************  FAILURE!!!  ************** com.sun.tools.javac.comp.Infer$InferenceException
TraceOut: (Speculative) (BASIC)  attempt to instantiate method: <T> requireNonNull(T,java.lang.String)T with arguments: java.lang.Object
TraceOut: Initial Bound Set (B0):
TraceOut:         Inference variable = T 
TraceOut: ***************************************  FAILURE!!!  ************** com.sun.tools.javac.comp.Infer$InferenceException
TraceOut: (Speculative) (BASIC)  attempt to instantiate method: <T> requireNonNull(T)T with arguments: java.lang.Object
TraceOut: Initial Bound Set (B0):
TraceOut:         Inference variable = T 
TraceOut: Bound set after Invocation Applicability Inference (B2): 
TraceOut:         Inference variable = T 
TraceOut:             T :> java.lang.Object
TraceOut: -------------  Inference variables to be solved: T
TraceOut: -------------   Performing graph inference step EQ_LOWER ----------
TraceOut: Bound set after resolution: 
TraceOut:         Inference variable = T instantiation = java.lang.Object 
TraceOut:             T :> java.lang.Object
TraceOut: Instantiated Method Type : (java.lang.Object)java.lang.Object
TraceOut: -----------------------------------------------

Process finished with exit code 0
```

**Comment by stephan-herrmann** [comment]
> * For `Test.A2<?> <: Test.A1<? extends T#0>` javac doesn't capture since the check for if a wildcard contains a type calls `isSubtypeNoCapture` when checking.
> 
> * For `? <= ? extends T#0` javac obtains `Test.B2` from the upper bound for the type variable.

Here JLS defines:
> A constraint formula of the form ‹S <: T› is reduced as follows: 
> * ...
> * ... the constraint reduces to true if T is among the supertypes of S

According to what we discussed right in #3457 `A2<?>` has supertype `A1<cap ?>`. I'd suppose that calling `isSubtypeNoCapture` is a left-over from the times before JLS §18 was written.

As for the interning of captures we have word that javac should likely do more in that regard.

I'd summarize this as two shortcomings in javac, that incidentally mask each other for testGH3457(). 

While the purpose of the current effort is to bring ecj closer to javac, I'm mostly interested in examples where javac is "smarter" but within the boundaries of JLS, be it with a grain of salt.

We may still have situations where interning is too aggressive, but I wouldn't give top priority to that issue for now.

**Comment by stephan-herrmann** [comment]
> while javac essentially gets `T#0 :> Test.B2` using this:
> 
> ```
> Reduced	⟨new TypeToken<A2<?>>() {
>           x() {
>             super();
>           }
>         } → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
>   to   	⟨new Test.TypeToken<Test.A2<?>>(){} → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
> Reduced	⟨new Test.TypeToken<Test.A2<?>>(){} → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
>   to   	⟨new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
> Reduced	⟨new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
>   to   	⟨Test.A2<?> <= ? extends Test.A1<? extends T#0>⟩
> Reduced	⟨Test.A2<?> <= ? extends Test.A1<? extends T#0>⟩
>   to   	⟨Test.A2<?> <: Test.A1<? extends T#0>⟩
> Reduced	⟨Test.A2<?> <: Test.A1<? extends T#0>⟩
>   to   	⟨? <= ? extends T#0⟩
> Reduced	⟨? <= ? extends T#0⟩
>   to   	⟨Test.B2 <: T#0⟩
> Reduced	⟨Test.B2 <: T#0⟩
>   to   	TypeBound  T#0 :> Test.B2
> ```

This kind of trace looks very helpful. @coehlrich could you provide hints to @srikanth-sankaran  where in the implementation you captured these values?

**Comment by coehlrich** [comment]
I just have a breakpoint for when the bound that needs to be checked is added and for the trace it was copy pasted from the ecj trace and changed to match what javac is doing based on the stack when the bound is added.

**Comment by srikanth-sankaran** [comment]
> I just have a breakpoint for when the bound that needs to be checked is added and for the trace it was copy pasted from the ecj trace and changed to match what javac is doing based on the stack when the bound is added.
> 
> 
> 
> 

Yes, that was my plan for next incremental improvement for trace emission. Stay tuned.

**Comment by stephan-herrmann** [comment]
I'm starting to think that JLS lacks a full section on this topic: when is it OK to unify captures / type variables? Despite the technical lingo of "interning", or "caching" this unification is an essential concept for type inference and type checking in general.

The latest example even crosses the border of different kinds of type variables: In #5053 I concluded that javac unifies:
* a "fresh type variable" introduced during 18.4 second attempt (ecj: CaptureBinding18)
* and a regular capture form evaluating a message invocation expression returning a wildcard parameterized type.

This seems to be mediated via a "capture bound", a concept of which I understood that it is intended to *avoid* real capturing during type inference.

**Comment by srikanth-sankaran** [comment]
> while javac essentially gets `T#0 :> Test.B2` using this:
> 
> ```
> Reduced	⟨new TypeToken<A2<?>>() {
>           x() {
>             super();
>           }
>         } → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
>   to   	⟨new Test.TypeToken<Test.A2<?>>(){} → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
> Reduced	⟨new Test.TypeToken<Test.A2<?>>(){} → Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
>   to   	⟨new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
> Reduced	⟨new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>⟩
>   to   	⟨Test.A2<?> <= ? extends Test.A1<? extends T#0>⟩
> Reduced	⟨Test.A2<?> <= ? extends Test.A1<? extends T#0>⟩
>   to   	⟨Test.A2<?> <: Test.A1<? extends T#0>⟩
> Reduced	⟨Test.A2<?> <: Test.A1<? extends T#0>⟩
>   to   	⟨? <= ? extends T#0⟩
> Reduced	⟨? <= ? extends T#0⟩
>   to   	⟨Test.B2 <: T#0⟩
> Reduced	⟨Test.B2 <: T#0⟩
>   to   	TypeBound  T#0 :> Test.B2
> ```
> 
> * For `new Test.TypeToken<Test.A2<?>>(){} <: Test.TypeToken<? extends Test.A1<? extends T#0>>` javac would capture.
> * For `Test.A2<?> <: Test.A1<? extends T#0>` javac doesn't capture since the check for if a wildcard contains a type calls `isSubtypeNoCapture` when checking.
> * For `? <= ? extends T#0` javac obtains `Test.B2` from the upper bound for the type variable.

With the latest tracing, this looks like this:

```
« <?...> error(...)»---------------- Begin Invocation Applicability Inference ---------------------
« <?...> error(...)»
« <?...> error(...)»        Add bound  T :> X.B2
« <?...> error(...)»                   ⇐ T :> X.B2
« <?...> error(...)»                   ⇐ (*** WITH NO CAPTURE ***) X.B2 <: T
« <?...> error(...)»                   ⇐ ? extends T >= ?
« <?...> error(...)»                   ⇐ (*** WITH NO CAPTURE ***) X.A2<?> <: X.A1<? extends T>
« <?...> error(...)»                   ⇐ ? extends X.A1<? extends T> >= X.A2<?>
« <?...> error(...)»                   ⇐ <anonymous X.TypeToken<X.A2<?>>> <: X.TypeToken<? extends X.A1<? extends T>>
« <?...> error(...)»                   ⇐ isSubtypeUnchecked(<anonymous X.TypeToken<X.A2<?>>>,X.TypeToken<? extends X.A1<? extends T>>)
« <?...> error(...)»                   ⇐ compatible(<anonymous X.TypeToken<X.A2<?>>>,X.TypeToken<? extends X.A1<? extends T>>)?
« <?...> error(...)»                   ⇐ check actual type <anonymous X.TypeToken<X.A2<?>>> against formal type X.TypeToken<? extends X.A1<? extends T>>
```
```

**Comment by stephan-herrmann** [comment]
> With the latest tracing, this looks like this:

Great! 

nitpick:

> `? extends T >= ?`

If this is to represent the notion of type argument contained by (is it?), then the canonical notation would be

 `? <= ? extends T`

 😄

**Comment by srikanth-sankaran** [comment]
> If this is to represent the notion of type argument contained by (is it?), then the canonical notation would be
> 
> `? <= ? extends T`

Yeah. Thing is, javac has this method `com.sun.tools.javac.code.Types#containsType(com.sun.tools.javac.code.Type, com.sun.tools.javac.code.Type)` and this other method `com.sun.tools.javac.code.Types#containedBy(com.sun.tools.javac.code.Type, com.sun.tools.javac.code.Type)`

I guess I could flip the notation to canonical form, but that may result in duplicate checks when the former ends up calling the latter. Anyway, I felt there is value in preserving the call chain. 

As long as you & I understand, some _apocryphal_ (!) notation wouldn't hurt 😆
