### ISSUE TITLE
Problem detected during type inference: expression has no value

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.core#4533]
Regression from https://github.com/eclipse-jdt/eclipse.jdt.core/commit/0300f7f64816c7d1a7d78e02f09793edef46b423 / https://github.com/eclipse-jdt/eclipse.jdt.core/pull/4517

The code below doesn't compile anymore with latest SDK build, reporting `Problem detected during type inference: expression has no value` compilation error. Reverting 0300f7f64816c7d1a7d78e02f09793edef46b423 fixes the error.

```
import java.util.function.Supplier;

public class X implements Foo {

    private final Foo delegate;
    private final Helper helper;

    public X(Helper helper, Foo delegate) {  
        this.helper = helper;
        this.delegate = delegate;
    }

    @Override
    public <T> void setProperty(T value) {
        helper.run(() -> delegate.setProperty(value));  // Problem detected during type inference: expression has no value
    }
}

interface Foo {
    public <T> void setProperty(T value);
}

interface Helper {
    public void run(Runnable runnable); // comment out this to see a different error
    public <R> R run(Supplier<R> supplier);
}
```

**Comment by iloveeclipse** [comment]
@stephan-herrmann : would be great if it could be fixed before M2 next week.

**Comment by stephan-herrmann** [comment]
How does the saying go? "Test cases are the breakfast of champions"? I don't remember exactly :wink:

yummy, thanks

**Comment by stephan-herrmann** [comment]
>     public void run(Runnable runnable); // comment out this to see a different error

those errors look legit to me:
```
----------
1. ERROR in /tmp/X.java (at line 15)
        helper.run(() -> delegate.setProperty(value));  // Problem detected during type inference: expression has no value
               ^^^
The method run(Supplier<R>) in the type Helper is not applicable for the arguments (() -> {})
----------
2. ERROR in /tmp/X.java (at line 15)
        helper.run(() -> delegate.setProperty(value));  // Problem detected during type inference: expression has no value
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Cannot return a void result
----------
```

@iloveeclipse  did you observe differently?

**Comment by iloveeclipse** [comment]
> did you observe differently?

No, they would be reported before, just wanted to highlight in case it would be relevant.

**Comment by iloveeclipse** [comment]
Thanks Stephan!
